### ISSUE TITLE
Escaping question marks in strings?

### ISSUE THREAD

**Issue by timdah** [craflin/mare#21]
Hi, I'm trying to add a specific linker flag
```
linkFlags += {
  "/INCLUDE:?warp_size@cuda@at@@YAHXZ"
}
```
but the question mark makes problems.
Without the question mark the flag is added to the VS project file, otherwise not.

Looked at the parser class and I guess the question mark is interpreted as if condition?

Is there a way to escape the question mark? I already tried backslash and single quotes.

**Comment by craflin** [comment]
I think it's probably interpreted as wildcard pattern (see Namespace.cpp:542). This is skipped if `word.flags is != 0`. In Word.cpp:56 we can see that some flag is set if the string is surrounded with ''''. So you can try:
```
linkFlags += {
  "\"/INCLUDE:?warp_size@cuda@at@@YAHXZ\""
}
```
However, I am not sure if this will have some side effects like an extra set of quotation marks in the generated command line.

**Comment by timdahlmanns** [comment]
Thanks a lot, that fixed it 👍
