### ISSUE TITLE
cppCompiler in cmake export

### ISSUE THREAD

**Issue by roefer** [craflin/mare#6]
It seems only the first part of the macro cppCompiler is used when mare is used to generate cmake files. We use
```
cppCompiler = {
    "env CCACHE_CPP2=yes $(utilDirRoot)/Buildchain/Linux/bin/ccache clang++ -D__extern_always_inline=inline"
```
and the CMakeLists.txt generated just contains
```
set(CMAKE_CXX_COMPILER "env")
```

**Comment by craflin** [comment]
Fixed!

**Comment by roefer** [comment]
Unfortunately, this does not work. Now the whole string is inserted in double quotes into the final build.make file and it is interpreted as the name of a single executable. I guess we have to put the line into a script.

**Comment by craflin** [comment]
Here are some suggestions: http://stackoverflow.com/questions/1815688/how-to-use-ccache-with-cmake

The symlink solutions is interesting. I guess, the following could work (untested):
set(ENV{CCACHE_CPP2} "yes")
set(CMAKE_CXX_COMPILER "somedir/Buildchain/Linux/bin/clang++") <-- symlink pointing to ccache
set(CMAKE_CXX_COMPILER_ID "Clang") <-- not sure if this is required
set_property(TARGET targetname PROPERTY COMPILE_DEFINITIONS "__extern_always_inline=inline")

Since mare can set up environment variables, "env" is actually no longer needed when mare is not used as a generator. I could add some code to the cmake generator to add set(ENV ..) to the generated CMakeLists.txt file. Then, given the solution above works, the declaration in the Marefile could look like:

cppCompiler = "CCACHE_CPP2=yes $(utilDirRoot)/Buildchain/Linux/bin/clang++"
defines += "__extern_always_inline=inline"

**Comment by craflin** [comment]
Well, I added the set(ENV...) code and tested this. It seems to work:

colin@colin-VirtualBox:~/git/mare/examples/helloworld$ cat Marefile 

linkFlags += {
  if tool == "vcxproj" { "/SUBSYSTEM:CONSOLE" }
}

cppCompiler = "CCACHE_CPP2=yes bin/g++"
defines += "__extern_always_inline=inline"

targets = {
  helloworld = cppApplication + {
    files = {
      "*.cpp" = cppSource
    }
  }
}
colin@colin-VirtualBox:~/git/mare/examples/helloworld$ ../../Debug/mare --cmake
CMakeLists.txt
helloworld/CMakeLists.txt
colin@colin-VirtualBox:~/git/mare/examples/helloworld$ mkdir build
colin@colin-VirtualBox:~/git/mare/examples/helloworld$ cd build/
colin@colin-VirtualBox:~/git/mare/examples/helloworld/build$ cmake ..
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/colin/git/mare/examples/helloworld/build
colin@colin-VirtualBox:~/git/mare/examples/helloworld/build$ make -n
/usr/bin/cmake -H/home/colin/git/mare/examples/helloworld -B/home/colin/git/mare/examples/helloworld/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/colin/git/mare/examples/helloworld/build/CMakeFiles /home/colin/git/mare/examples/helloworld/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make -f helloworld/CMakeFiles/helloworld.dir/build.make helloworld/CMakeFiles/helloworld.dir/depend
cd /home/colin/git/mare/examples/helloworld/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/colin/git/mare/examples/helloworld /home/colin/git/mare/examples/helloworld/helloworld /home/colin/git/mare/examples/helloworld/build /home/colin/git/mare/examples/helloworld/build/helloworld /home/colin/git/mare/examples/helloworld/build/helloworld/CMakeFiles/helloworld.dir/DependInfo.cmake --color=
make -f helloworld/CMakeFiles/helloworld.dir/build.make helloworld/CMakeFiles/helloworld.dir/build
/usr/bin/cmake -E cmake_progress_report /home/colin/git/mare/examples/helloworld/build/CMakeFiles 1
/usr/bin/cmake -E cmake_echo_color --switch= --green "Building CXX object helloworld/CMakeFiles/helloworld.dir/__/main.cpp.o"
cd /home/colin/git/mare/examples/helloworld/build/helloworld && /home/colin/git/mare/examples/helloworld/helloworld/../bin/g++   -D__extern_always_inline=inline  -o CMakeFiles/helloworld.dir/__/main.cpp.o -c /home/colin/git/mare/examples/helloworld/main.cpp
/usr/bin/cmake -E cmake_echo_color --switch= --red --bold "Linking CXX executable ../../Debug/helloworld"
cd /home/colin/git/mare/examples/helloworld/build/helloworld && /usr/bin/cmake -E cmake_link_script CMakeFiles/helloworld.dir/link.txt --verbose=
/usr/bin/cmake -E cmake_progress_report /home/colin/git/mare/examples/helloworld/build/CMakeFiles  1
echo "Built target helloworld"
/usr/bin/cmake -E cmake_progress_start /home/colin/git/mare/examples/helloworld/build/CMakeFiles 0
colin@colin-VirtualBox:~/git/mare/examples/helloworld/build$ make
Scanning dependencies of target helloworld
[100%] Building CXX object helloworld/CMakeFiles/helloworld.dir/__/main.cpp.o
Linking CXX executable ../../Debug/helloworld
[100%] Built target helloworld

**Comment by roefer** [comment]
The official way to use ccache with seems to be this one:
```
SET_PROPERTY(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
```
