### ISSUE TITLE
"writeFile" does not create full path to file

### ISSUE THREAD

**Issue by bhuman** [craflin/mare#9]
Since "writeFile" is a macro that is evaluated at the beginning of the build process, it is a problem that it does not create the full path to the location of the file. When building from scratch, the build directory does not yet exist, which means that "writeFile" cannot be used to create files inside the build directory.

**Comment by craflin** [comment]
Well, to be honest, I have not tested it. But the line of code that I added should do the job. Let me know if it does not.
